[project]
authors = ["Benoit D. <benoit.dequidt@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-cpp-py"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
configure = "cmake -GNinja -Bbuild -S."
pytest = "pytest"

[dependencies]
gcc = ">=14.2.0,<14.3"
gxx = ">=14.2.0,<14.3"
cmake = ">=3.31.2,<4"
ninja = ">=1.12.1,<2"
python = ">=3.13.1,<3.14"
pytest = ">=8.3.4,<9"
