[project]
authors = ["Benoit D. <benoit.dequidt@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-cpp-py"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
